version: "3.7"

services:
    app:
        build:
            args:
                user: appuser
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: eventapp-image
        container_name: eventapp-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
        - ./:/var/www
        networks:
        - eventapp-network

    nginx:
        image: nginx:1.17-alpine
        container_name: eventapp-nginx
        restart: unless-stopped
        ports:
        - 8000:80
        volumes:
        - ./:/var/www
        - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
        - eventapp-network

networks:
  eventapp-network:
    driver: bridge
