version: "3.7"

services:
    app:
        build:
            # args:
            #     user: appuser
            #     uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: eventapp-image
        container_name: eventapp-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
        - ./:/var/www
        networks:
        - eventapp-network

    nginx:
        image: nginx:1.17-alpine
        # environment:
        #     - SERVER_NAME=192.168.0.162
        container_name: eventapp-nginx
        restart: unless-stopped
        ports:
        - 9000:80
        - "443:443"
        volumes:
        - ./:/var/www
        - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./docker-compose/nginx/entrypoint.sh:/entrypoint.sh
        entrypoint: /entrypoint.sh
        networks:
        - eventapp-network

networks:
  eventapp-network:
    driver: bridge
