openapi: 3.0.0
info:
  title: Coronatime API
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://producation.app/api
    description: production server

paths:
  /users:
    get:
      summary: Returns a list of users.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /organizer:
    post:
        summary: Create an organizer.
        parameters:
          - name: name
            in: body request
            description: organizer name
            required: true
            schema:
            type: string
          - name: activity_area
            in: body request
            description: organizer activity area
            required: true
            schema:
            type: string
          - name: logo
            in: body request
            description: organizer logo
            required: false
            schema:
            type: file
          - name: description
            in: body request
            description:
            required: true
            schema:
            type: text
        description: A JSON array of the details of the entity created
           content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        responses:
        '200':
          description: A JSON array of the details of the entity created
           content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: A string telling Validation fails.


    delete:
        summary: Delete an organizer entity passing his id.
        parameter:
        - name: id
          in: query
          description: organizer id
          required: true
          schema:
          type: string
        responses:
        '200':
          description: A String confirming the entity is deleted
        '404':
          description: A String telling the entity can't be found



    get:
     summary: Returns the details of the organizer by passing his id.
     parameter:
      - name: id
        in: query
        description: organizer id
        required: true
        schema:
        type: string
      responses:
        '200':
          description: A JSON array of the organizer details
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '404':
          description: A String telling the entity can't be found




    post:
            summary: Update an organizer by passing his id.
            - name: id
              in: query
              description: organizer id
              required: true
              schema:
              type: string
            responses:
            '200':
              description: A JSON array of the new details of the entity created
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: string
            '400':
              description: A string telling Validation fails.


  /sponsor:
    post:
        summary: Create an sponsor.
        - name: name
            in: body request
            description: sponsor name
            required: true
            schema:
            type: string
        - name: activity_sector
            in: body request
            description: sponsor activity sector
            required: true
            schema:
            type: string
        - name: logo
            in: body request
            description:
            required: false
            schema:
            type: file
        - name: type
            in: body request
            description: sponsor type
            required: true
            schema:
            type: text
        - name: description
            in: body request
            description:
            required: true
            schema:
            type: text
        responses:
        '200':
          description: A JSON array of the details of the entity created
           content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: A string telling Validation fails.


    delete:
        summary: Delete an sponsor entity passing his id.
        - name: id
            in: query
            description: sponsor id
            required: true
            schema:
            type: string
        responses:
        '200':
          description: A String confirming the entity is deleted
        '404':
          description: A String telling the entity can't be found



    get:
     summary: Returns the details of the sponsor by passing his id.
      - name: id
            in: query
            description: sponsor id
            required: true
            schema:
            type: string
      responses:
        '200':
          description: A JSON array of the sponsor details
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '404':
                  description: A String telling the entity can't be found

    get:
        summary: Returns a list of the sponsors related to an event by passing the event id.
         - name: id
            in: query
            description: event id
            required: true
            schema:
            type: string
          responses:
            '200':
              description: A JSON array of the sponsor details
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: string
            '404':
                      description: A String telling the entity can't be found

    post:
            summary: Update an sponsor by passing his id.
            - name: id
              in: query
              description: sponsor id
              required: true
              schema:
              type: string
              responses:
            '200':
              description: A JSON array of the new details of the entity created
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: string
            '400':
              description: A string telling Validation fails.

